source 'https://github.com/CocoaPods/Specs.git'

target 'segmentio-simple', :exclusive => true do
  pod "segmentio-simple", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "segmentio-simple", :path => "../"

  pod 'CCLRequestReplay', :git => 'https://github.com/cocodelabs/CCLRequestReplay.git'
  pod 'Expecta'
  pod 'Specta'
end
